### ISSUE TITLE
Improve command-line argument parsing

### ISSUE THREAD

**Issue by micheledallerive** [swystems/det-bypass#2]
Improve the current fixed-position command-line arguments to allow better customization and ease of use.

Taking `pp_poll.c` as an example, currently the program arguments (for the client) are:
`./pp_poll <device name> start <# packets> <interval ns> <server ip>`

It could be transformed in a "flag-based" argument passing, to allow arguments to be out of order and optional arguments to exist.
For example, the new arguments could be:
`./pp_poll <device name> start [-n <# of packets>] [-i <interval ns>] [-s <server ip>] [-p <persistence type (all timestamps, min/max, buckets>]`.

Using some function like [`getopt`](https://www.gnu.org/software/libc/manual/html_node/Using-Getopt.html) could make the args parsing more maintainable.

**Comment by dvr0** [comment]
Closed in #4
